language: c

sudo: required
dist: trusty
services: docker
os:
 - linux
 - linux-ppc64le

before_install:
 - ./docker/build-builder

script:
 - ./docker/build-pb --check --verbose --configure-opts "--enable-platform-arm64 --enable-platform-powerpc"
